version: '3.8'

services:
  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  database:
    image: mariadb:11.2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: calculations
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: ./MiddleTire
    ports:
      - "8080:8080"
    depends_on:
      - database
      - sonarqube

  frontend:
    build: ./Frontend
    ports:
      - "3000:80"
    depends_on:
      - api
      - sonarqube

  testcafe:
    image: testcafe/testcafe
    volumes:
      - ./Frontend/tests:/tests
    working_dir: /tests
    command: "chromium e2e_test.js"
    depends_on:
      - frontend

  k6:
    image: grafana/k6
    volumes:
      - ./tests:/scripts
    working_dir: /scripts
    command: run spike_test.js
    depends_on:
      - api

volumes:
  db_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
